### ISSUE TITLE
Vertaisarvio

### ISSUE THREAD

**Issue by ArtKoski** [sallasal/Tapahtumabudjetti#1]
Testattu 11.8.2020

Rekisteröityminen
- Pystyin luomaan käyttäjän jättämällä kohtia tyhjäksi. Tein käyttäjän ilman sähköpostia ja salasanaa, ja myös käyttäjä ilman nimeä onnistui.
- Ehdotus: Validointi esimerkiksi siten, että syötteissä on minimi- ja maksimirajoitteet.

Login/Logout
- Toimi odotetusti 

Tapahtumat
- Muiden tapahtumien katselu onnistuu
- Lisäsin oman tapahtuman, ja lisäsin siihen uuden osa-alueen. Tapahtuman budjetti muuttui tästä odotetusti.
- Kun koitin lisätä maksun tapahtumaan, sain virheen “Maksun lisääminen ei onnistunut”. Kokeilin vaihtaa arvoja (saajan nimi, maksun syy, summa, maksupäivä, kategoria check/uncheck), käyttäjää ja tapahtumaa, mutta sama virhe toistui.

Koodi
-Näyttää melko puhtaalta. Kommentit helpottivat koodin lukemista. En siis huomannut mitään mistä huomauttaa.

Ehdotuksia:
-Mukavuutta sovelluksen käyttöön toisi jonkinlainen ulkoasu

**Comment by sallasal** [comment]
Moi,
kiitos hyvästä palautteesta! Olen ilmaissut kyllä tosi epäselvästi tuon maksun lisäyksen vaatimukset, kun ne oli epäselvät sekä sinulle että ohjaajalle. Hyvä että sanoitte, koetan saada tota nyt kovasti selkeämmäksi muillekin kuin itselleni :D
